server:
  port: 5003
#
spring:
  datasource:
    url: jdbc:oracle:thin:@//10.211.55.6:1521/orclpdb
    username: aron
    password: aron
    #    driver-class-name: oracle.jdbc.driver.OracleDriver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
---
spring:
  application:
    name: my-app
  profiles:
    active: dev
  datasource:
    url: jdbc:oracle:thin:@//10.211.55.6:1521/orclpdb
    username: aron
    password: aron
  #    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    #    hibernate:
    #      ddl-auto: create
    show_sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    open-in-view: true
server:
  port: 5003
---
spring:
  cache:
    type: ehcache
    #    type: redis
    ehcache:
      config: classpath:ehcache.xml
---
#spring:
#  kafka:
#    consumer:
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.aron.kafka.dto.gson
#spring:
#  redis:
#    host: localhost
#    port: 6379
#    password: woshixuhu1217